#
# This is free software, lisence use MIT.
# 
# Copyright (C) 2020 KFERMercer <KFER.Mercer@gmail.com>
# 
# <https://github.com/KFERMercer/OpenWrt-CI>
#

name: Merge-upstream
on:
  push:
    paths:
      - '.github/workflows/upstream.yml'
  schedule:
    - cron: 0 */12 * * *
  watch:
    types: started
  repository_dispatch:

jobs:
  merge:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: Ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: master
        fetch-depth: 0
        lfs: true

    - name: Set git identity
      run : |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"

    - name: Syn upstream
      run: |
        rm -rf `find -maxdepth 1 -type d -name "[!.]*" ! -path "./diy"`
        git rm -r --cache *
        git clone --depth 1 https://github.com/garypang13/my-packages && mv -f my-packages/* ./ ; rm -Rf my-packages
        git clone --depth 1 https://github.com/garypang13/luci-app-bypass
        git clone --depth 1 https://github.com/garypang13/luci-app-dnsfilter
        git clone --depth 1 https://github.com/garypang13/openwrt-static-qb && mv -f openwrt-static-qb/* ./ ; rm -Rf openwrt-static-qb
        git clone --depth 1 https://github.com/garypang13/aria2
        git clone --depth 1 https://github.com/garypang13/openwrt-smartdns && mv -f openwrt-smartdns/* ./ ; rm -Rf openwrt-smartdns
        git clone --depth 1 https://github.com/garypang13/openwrt-adguardhome AdGuardHome
        git clone --depth 1 https://github.com/garypang13/luci-app-eqos
        git clone --depth 1 https://github.com/garypang13/luci-app-amule
        git clone --depth 1 https://github.com/garypang13/luci-app-xlnetacc
        git clone --depth 1 https://github.com/garypang13/luci-app-baidupcs-web
        git clone --depth 1 https://github.com/garypang13/luci-theme-edge
        git clone --depth 1 https://github.com/garypang13/autosamba
        git clone --depth 1 https://github.com/garypang13/luci-app-homebridge
        git clone --depth 1 https://github.com/garypang13/openwrt-openvpn && mv -f openwrt-openvpn/* ./ ; rm -Rf openwrt-openvpn

        git clone --depth 1 https://github.com/jerrykuku/luci-theme-argon
        git clone --depth 1 https://github.com/jerrykuku/luci-app-vssr
        git clone --depth 1 https://github.com/jefferymvp/luci-app-koolproxyR
        git clone --depth 1 https://github.com/peter-tank/luci-app-dnscrypt-proxy2
        git clone --depth 1 https://github.com/brvphoenix/luci-app-wrtbwmon
        git clone --depth 1 https://github.com/sirpdboy/luci-app-advanced
        git clone --depth 1 https://github.com/jerrykuku/luci-app-jd-dailybonus
        git clone --depth 1 https://github.com/vernesong/OpenClash && mv -f OpenClash/luci-app-openclash ./ ; rm -Rf OpenClash
        git clone --depth 1 https://github.com/NateLol/luci-app-oled
        git clone --depth 1 https://github.com/destan19/OpenAppFilter && mv -n OpenAppFilter/* ./ ; rm -Rf OpenAppFilter
        git clone --depth 1 https://github.com/esirplayground/luci-app-poweroff
        git clone --depth 1 https://github.com/lvqier/luci-app-dnsmasq-ipset
        git clone --depth 1 https://github.com/sirpdboy/luci-app-netdata
        git clone --depth 1 https://github.com/small-5/ddns-scripts-dnspod
        git clone --depth 1 https://github.com/small-5/ddns-scripts-aliyun
        git clone --depth 1 https://github.com/walkingsky/luci-wifidog luci-app-wifidog
        git clone --depth 1 https://github.com/peter-tank/luci-app-autorepeater
        git clone --depth 1 https://github.com/zzsj0928/luci-app-serverchand
        git clone --depth 1 https://github.com/CCnut/feed-netkeeper && mv -n feed-netkeeper/* ./ ; rm -Rf Rffeed-netkeeper

        svn co https://github.com/lisaac/luci-app-dockerman/trunk/applications/luci-app-dockerman
        svn co https://github.com/Lienol/openwrt/trunk/package/network/fullconenat && rm -f fullconenat/patches/000-printk.patch
        svn co https://github.com/srchack/custom-packages/trunk/open-vm-tools
        svn co https://github.com/Lienol/openwrt/trunk/package/lean/luci-app-autoreboot
        svn co https://github.com/NoTengoBattery/openwrt-mt7621/trunk/feeds/luci/applications/luci-app-compressed-memory
        svn co https://github.com/NoTengoBattery/openwrt-mt7621/trunk/package/system/compressed-memory
        svn co https://github.com/Tencent-Cloud-Plugins/tencentcloud-openwrt-plugin-ddns/trunk/tencentcloud_ddns
        svn co https://github.com/teasiu/dragino2/trunk/package/teasiu/luci-app-phtunnel
        svn co https://github.com/teasiu/dragino2/trunk/package/teasiu/phtunnel
        svn co https://github.com/coolsnowwolf/lede/trunk/package/network/services/shellsync
        svn co https://github.com/coolsnowwolf/packages/trunk/net/miniupnpd
        svn co https://github.com/coolsnowwolf/packages/trunk/net/mwan3
        svn co https://github.com/brvphoenix/wrtbwmon/trunk/wrtbwmon
        svn co https://github.com/project-openwrt/packages/trunk/lang/node-yarn
        
        rm -rf .svn
        echo -e "\q" | svn co https://github.com/project-openwrt/openwrt/branches/master/package/lean ./
        rm -rf .svn
        echo -e "\q" | svn co https://github.com/coolsnowwolf/lede/trunk/package/lean ./
        rm -rf .svn
        git clone --depth 1 https://github.com/xiaorouji/openwrt-passwall && mv -n openwrt-passwall/* ./ ; rm -Rf openwrt-passwall
        echo -e "\q" | svn co https://github.com/project-openwrt/openwrt/branches/master/package/ctcgfw ./
        rm -rf .svn
        svn export --force https://github.com/project-openwrt/openwrt/branches/master/package/ntlf9t && mv -n ntlf9t/* ./ ; rm -rf ntlf9t
        rm -rf .svn
        echo -e "\q" | svn co https://github.com/project-openwrt/openwrt/branches/master/package/zxlhhyccc ./
        rm -rf .svn
        echo -e "\q" | svn co https://github.com/project-openwrt/openwrt/branches/master/package/lienol ./
        rm -rf .svn
        git clone --depth 1 https://github.com/Lienol/openwrt-package && mv -n openwrt-package/* ./ ; rm -rf openwrt-package

    - name: SSH connection to Actions
      uses: garypang13/debugger-action@master
      if: 1 == 0

    - name: Modify
      run: |
        rm -Rf */.git */.svn qt5 openwrt-{chinadns*,simple-obfs,v2ray-plugin,fullconenat} cups* \
        mt-drivers coremark luci-app-{flowoffload,sfe,appfilter,unblockneteasemusic*,docker,adbyby-plus,advancedsetting,softethervpn} fcgiwrap \
        ddns-scripts_{aliyun,dnspod} UnblockNeteaseMusicGo ipv6-helper adbyby
        mv mt/drivers mt/mt-drivers
        cp -Rf mt/* ./ && rm -Rf mt
        sed -i "/minisign:minisign/d" luci-app-dnscrypt-proxy2/Makefile
        sed -i 's/+docker-ce/+docker \\\n\t+dockerd/' luci-app-dockerman/Makefile
        rm -f subconverter/patches/010-missing-header.patch
        sed -i 's?../../luci.mk?$(TOPDIR)/feeds/luci/luci.mk?g' */Makefile
        sed -i 's?../../lang?$(TOPDIR)/feeds/packages/lang?g' */Makefile
        cp -rf luci-app-mentohust/luasrc/luci/* luci-app-mentohust/luasrc/ && rm -Rf luci-app-mentohust/luasrc/luci
        bash diy/create_acl_for_luci.sh -a || true
        bash diy/convert_translation.sh -a || true
        rm -Rf antileech/src && git clone https://github.com/persmule/amule-dlp.antiLeech antileech/src
        sed -i '/\/etc\/config\/AdGuardHome/a /etc/config/AdGuardHome.yaml' luci-app-adguardhome/Makefile
        sed -i 's/+rclone\( \|$\)/+rclone +fuse-utils\1/g' luci-app-rclone/Makefile
        sed -i 's/ca-certificates/ca-bundle/g' */Makefile
        sed -i 's/ +kmod-fs-exfat//g' automount/Makefile
        sed -i 's/+libcap /+libcap +libcap-bin /' luci-app-openclash/Makefile
        sed -i 's/+docker-ce/+docker/g' luci-app-dockerman/Makefile
        find */luasrc/view/ -maxdepth 2 -name "*.htm" | xargs -i sed -i 's?"http://" + window.location.hostname?window.location.protocol + "//" + window.location.hostname?g' {}
        getversion() {
        	ver=$(basename $(curl -Ls -o /dev/null -w %{url_effective} https://github.com/$1/releases/latest) | grep -o -E "[0-9].+")
        	[ $ver ] && echo $ver || git ls-remote --tags git://github.com/$1 | cut -d/ -f3- | sort -t. -nk1,2 -k3 | awk '/^[^{]*$/{version=$1}END{print version}' | grep -o -E "[0-9].+"
        }
        sed -i "s/PKG_VERSION:=.*/PKG_VERSION:=$(getversion v2fly/v2ray-core)/g" v2ray/Makefile
        sed -i "s/PKG_VERSION:=.*/PKG_VERSION:=$(getversion XTLS/Xray-core)/g" xray/Makefile
        find ./*/ -maxdepth 1 -name "Makefile" ! -path "*tinyfecvpn*" | xargs -i sed -i "s/PKG_HASH:=.*/PKG_HASH:=skip/g" {}
        sed -i 's/SUBDIRS=/M=/g' */Makefile

    - name: Apply patches
      run: find "diy/patches" -type f -name '*.patch' -print0 | sort -z | xargs -I % -t -0 -n 1 sh -c "cat '%'  | patch -d './' -p1 -E --forward --no-backup-if-mismatch"

    - name: Apply
      run: |
        git add .
        git commit -m "update" || true
        git push
        
    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 3
