name: Build and release (tun)

on:
  push:
    tags:
      - 'v*'

jobs:

  build:
    name: Build and release (tun)
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    steps:

      - name: Check out
        uses: actions/checkout@v2.3.4

      - name: Get tag
        uses: olegtarasov/get-tag@v2
        id: tagName

      - name: Get time
        uses: gerred/actions/current-time@master
        id: current-time

      - name: Build
        uses: crazy-max/ghaction-xgo@v1.6.1
        env:
          TIME: "${{ steps.current-time.outputs.time }}"
        with:
          xgo_version: latest
          go_version: latest
          dest: dist
          prefix: hysteria
          targets: linux/amd64,linux/386,linux/arm-5,linux/arm-7,linux/arm64,linux/mipsle,darwin-10.12/amd64,darwin-10.12/arm64,windows-6.0/amd64,windows-6.0/386
          ldflags: -w -s -X main.appVersion=${{ env.GIT_TAG_NAME }} -X main.appCommit=${{ github.sha }} -X main.appDate=${{ env.TIME }}
          pkg: cmd

      - name: Upload
        uses: meeDamian/github-release@v2.0.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          gzip: false
          allow_override: true
          files: >
            ./dist/hysteria-linux-amd64
            ./dist/hysteria-linux-386
            ./dist/hysteria-linux-arm-5
            ./dist/hysteria-linux-arm-7
            ./dist/hysteria-linux-arm64
            ./dist/hysteria-linux-mipsle
            ./dist/hysteria-darwin-10.12-amd64
            ./dist/hysteria-darwin-10.12-arm64
            ./dist/hysteria-windows-6.0-amd64.exe
            ./dist/hysteria-windows-6.0-386.exe
