include $(TOPDIR)/rules.mk

LUCI_TITLE:=Default Settings
LUCI_DEPENDS:=+luci-base +@LUCI_LANG_zh_Hans
PKG_MAINTAINER:=
PKG_LICENSE:=GPL-3.0-or-later

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature



