language: c

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install dnsutils
  - sudo pip install gcovr
  - ./autogen.sh
  - ./configure

script:
  - ./.jenkins.sh
